base_path: ../../../../data/
runs_folder: validation/
filename: trajectory.csv
dir_txt: overlap_matrix_Roundabout.txt
folder_list:                      # if the folder_list is empty, it uses all folders in run_folder.
  - Roundabout01-Aeva
  - Roundabout01-Ouster
  - Roundabout01-Avia
  - Roundabout01-Velodyne

